# Generated by Django 4.1 on 2023-01-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='category',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='num_of_items',
            field=models.IntegerField(verbose_name=''),
        ),
    ]
