# Generated by Django 4.1 on 2023-01-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_fileinput_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinput',
            name='files',
            field=models.FileField(upload_to='excel/', verbose_name=''),
        ),
    ]
