# Generated by Django 4.1 on 2023-01-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_fileinput_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='category',
            field=models.CharField(blank=True, max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='num_of_items',
            field=models.IntegerField(blank=True, verbose_name=''),
        ),
    ]
